### ISSUE TITLE
Don't need to use range

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinopython101manual#14]
ConvertToUVW function on page 102 can be rewritten as

``` python
def ConvertToUVW(idSrf, pXYZ):
    pUVW = []
    for point in pXYZ:
        u, v = rs.SurfaceClosestPoint(idSrf, point)
        surface_xyz = rs.EvaluateSurface(idSrf, u, v)
        surface_normal = rs.SurfaceNormal(idSrf, (u,v))
        dirPos = rs.PointAdd(surface_xyz, surface_normal)
        dirNeg = rs.PointSubtract(surface_xyz, surfacenormal)
        dist = rs.Distance(surface_xyz, point)
        if (rs.Distance(point, dirPos) > rs.Distance(point, dirNeg)): dist *= -1
        pUVW.append((u, v, dist))
    return pUVW
```

**Comment by sbaer** [comment]
Same for GrevilleNormals function on page 103. just iterate over the uvGreville.  We can even use list comprehension in this case

``` python
def GrevilleNormals(idSrf):
    uvGreville = rs.SurfaceEditPoints(idSrf, True, True)
    srfNormals = [rs.SurfaceNormal(idSrf, grev) for grev in uvGreville]
    return srfNormals
```

**Comment by AvdHarten** [comment]
Can we talk about this one a little. I like that the syntax  becomes very concise, and compact, and probably more efficient, frankly...

Moving from VB to python, I think this kind of syntax daunted me a little when I first saw it. I figured the reason Skylar and I were good people to begin to write these things is because we have some sensitivity to what simple syntax to learn is, and what someone just learning might find more difficult. I wonder if this isn't one of those things.

On the other hand, this is coming in towards the end of the manual, and so if more concise, yet harder to grasp concepts are going to appear, it isn't a bad place for them... Thoughts?

Arthur

**Comment by sbaer** [comment]
These are both after page 100 in the manual. I figure by this point it is better to show concise code that the student should be able to grasp.

Of course this is just my opinion and that doesn't buy much.

**Comment by SJET** [comment]
I agree with Steve - let's keep it.

Skylar

---

**_Skylar Tibbits_
TED Fellow 2011
www.sjet.us http://www.sjet.us/

**Comment by AvdHarten** [comment]
Ok. Sounds good.
